// Generated file. Do not edit.
// This file is generated by the iFlutter

// ignore_for_file: constant_identifier_names
// ignore_for_file: lines_longer_than_80_chars
class AssetsRes {
  AssetsRes._();

  static const String PROJECT_NAME = 'associations_app';
  static const String PROJECT_VERSION = '1.0.1+1';
  static const String FB_LOGO = 'assets/fb_logo.svg';
  static const String IMG_PERSON = 'assets/img_person.jpg';
  static const String INSTA_LOGO = 'assets/insta_logo.svg';
  static const String THE_ASSOCIATES = 'assets/the-associates.png';
  static const String THE_ASSOCIATES_LOGO = 'assets/the-associates_logo.png';
}
