// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB6mMVBdS-s-TdJElulsiPpfIdZ4r53Rog',
    appId: '1:249111785493:web:cb7583a01c83b6b57a1e1c',
    messagingSenderId: '249111785493',
    projectId: 'kmf-digital-id',
    authDomain: 'kmf-digital-id.firebaseapp.com',
    storageBucket: 'kmf-digital-id.firebasestorage.app',
    measurementId: 'G-ZQ2T826830',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAfAman6z4LlFFqmVO5tEtBtaiNm4IH0QI',
    appId: '1:249111785493:android:542f0ea950401f987a1e1c',
    messagingSenderId: '249111785493',
    projectId: 'kmf-digital-id',
    storageBucket: 'kmf-digital-id.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBei8S-zSx41vN_l_ZrbHJVY0UobYiGmJ8',
    appId: '1:249111785493:ios1:9c7a5c87e8abd33e7a1e1c',
    messagingSenderId: '249111785493',
    projectId: 'kmf-digital-id',
    storageBucket: 'kmf-digital-id.firebasestorage.app',
    iosBundleId: 'com.skaktech.kmfdigitalid',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBei8S-zSx41vN_l_ZrbHJVY0UobYiGmJ8',
    appId: '1:249111785493:ios1:9c7a5c87e8abd33e7a1e1c',
    messagingSenderId: '249111785493',
    projectId: 'kmf-digital-id',
    storageBucket: 'kmf-digital-id.firebasestorage.app',
    iosBundleId: 'com.skaktech.kmfdigitalid',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB6mMVBdS-s-TdJElulsiPpfIdZ4r53Rog',
    appId: '1:249111785493:web:09b19c6a4a5fff157a1e1c',
    messagingSenderId: '249111785493',
    projectId: 'kmf-digital-id',
    authDomain: 'kmf-digital-id.firebaseapp.com',
    storageBucket: 'kmf-digital-id.firebasestorage.app',
    measurementId: 'G-4KHTJ4529B',
  );
}
